### ISSUE TITLE
CSS3 Detection

### ISSUE THREAD

**Issue by arian** [minhlong139/BorderRadius#1]
Hi, Very nice script you've got... but you shouldn't test by Browser engine for CSS3 border-radius support, you should test on the browser capabilities.. I've a script, mooModernizr (http://github.com/arian/mooModernizr) which tests a lot of CSS3/HTML5 features. You can grab the border-radius test from it...

Or maybe something like this, ( http://yura.thinkweb2.com/cft/ ):

```
var checkBorderRadius = function(){
    var docEl = document.documentElement, s;
    if (docEl && (s = docEl.style)) {
        return (typeof s.borderRadius == 'string'
            || typeof s.MozBorderRadius == 'string'
            || typeof s.WebkitBorderRadius == 'string'
            || typeof s.KhtmlBorderRadius == 'string');
        }
    return null;
}
```

**Comment by minhlong139** [comment]
Many thanks arian,

I will put your idea into my BorderRadius
