### ISSUE TITLE
images support

### ISSUE THREAD

**Issue by tenchi** [minhlong139/BorderRadius#2]
I cant work this script on img element on ie8 in ie7 compability mode. Not tested yet on other configurations. I dont know if it is not implemented or a bug, but if it is not implemented, i think a little test on each element targeted by the script will avoid throwing errors. Anyway this is a great utility. thank you.

**Comment by minhlong139** [comment]
Thank for your issue,

My answer is not implemented yet. I will improve it soon.

Btw, good luck, tenchi!

**Comment by tenchi** [comment]
;-)
